import turtle
Turtle = turtle.Turtle()

Turtle.hideturtle()
Turtle.right(45)
Turtle.forward(50)
Turtle.back(50)
Turtle.right(90)
Turtle.forward(50)
Turtle.back(50)
Turtle.right(135)
Turtle.forward(50)
Turtle.left(90)
Turtle.forward(40)
Turtle.back(40)
Turtle.right(180)
Turtle.forward(20)
Turtle.left(45)
Turtle.forward(40)
Turtle.back(40)
Turtle.right(45)
Turtle.left(90)
Turtle.penup()
Turtle.forward(20)
Turtle.pendown()
Turtle.circle(20)
Turtle.left(90)
Turtle.penup()
Turtle.forward(20)
Turtle.pendown()
Turtle.dot(3)
Turtle.penup()
Turtle.right(90)
Turtle.forward(5)
Turtle.left(90)
Turtle.forward(5)
Turtle.pendown()
Turtle.dot(3, "blue")
Turtle.penup()
Turtle.back(10)
Turtle.pendown()
Turtle.dot(3, "blue")
Turtle.left(90)
Turtle.penup()
Turtle.forward(10)
Turtle.right(90)
Turtle.pendown()
Turtle.forward(10)


turtle.done()